[package]
name = "dono"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.17"
dotenv = "0.15.0"
reqwest = "0.11.11"
serde = "1.0.143"
tokio = "1.20.1"
graphql_client = "*"
