github_user_token = "your_token"
native_colors = false # set to true if you want to use colors from github API
fill = "■"
empty = "■"

[colors]
empty = "#161b22"
low = "#0e4429"
medium = "#006d32"
high = "#26a641"
max = "#39d353"
